server:
  port: 2000
spring:
  application:
    name: CheckingOutRestTestClient
todo:
  file:
    path: data/todo.json
    format: json
#todo:
#  file:
#    path: data/todo.xml
#    format: xml

api:
  endpoint:
    baseurl: /api/v1/todo
